#!/usr/bin/env bash

view () {

    dir=$(dirname "$0")
    plan="$dir/stundenplanWS19_20.csv"

    
    day="$1"
    # printf "\n"

    while true
    do
        # tput sc
        if [ -z "$1" ]; then
            read -p 'day Regex: ' day
        fi
        # tput rc; tput ed
        printf "\033[1A"; printf "\033[K"
        if [[ ! -z "$day" ]]; then
            read -p 'time? y/n [y] ' time
            printf "\033[1A"; printf "\033[K" # tput rc; tput ed
            case $time in
                y)
                    time="$time"                   
                    ;;
                n)
                    time=
                    ;;
                *)
                    time='y'
                    ;;
            esac
            read -p 'name? y/n [y] ' name
            printf "\033[1A"; printf "\033[K" # tput rc; tput ed           
            case $name in
                y)
                    name="$name"
                    ;;
                n)
                    name=
                    ;;
                *)
                    #echo 'what?'
                    name='y'
                    ;;
            esac
            read -p 'location y/n [n] ' loc
            printf "\033[1A"; printf "\033[K" # tput rc; tput ed
            case $loc in
                y)
                    loc="$loc"
                    ;;
                n)
                    loc=
                    ;;
                *)
                    loc=
                    ;;
            esac           
            if [ -z "$time" ] && [ -z "$name" ] && [ -z "$loc" ]; then
                printf "you kidding?\n"
                exit
            fi
            break
        else
            printf "aborting.\n"
            exit
        fi
    done
    

    if [ -z "$time" ] && [ -z "$name" ]; then
        head -1000 $plan \
            | grep "$day" -a \
            | awk -F"," '{print $10}'
    elif [ -z "$time" ] && [ -z "$loc" ]; then
        head -1000 $plan \
            | grep "$day" -a \
            | awk -F"," '{print $7, $8}'
    elif [ -z "$name" ] && [ -z "$loc" ]; then
        head -1000 $plan \
            | grep "$day" -a \
            | awk -F"," '{print $1, $3}'
    elif [ -z "$time" ]; then
        head -1000 $plan \
            | grep "$day" -a \
            | awk -F"," '{print $7, $8, $10}'
    elif [ -z "$name" ]; then
        head -1000 $plan \
            | grep "$day" -a \
            | awk -F"," '{print $1, $3, $10}'
    elif [ -z "$loc" ]; then
        head -1000 $plan \
            | grep "$day" -a \
            | awk -F"," '{print $1, $3, $7, $8}'
    else
        head -1000 $plan \
            | grep "$day" -a \
            | awk -F"," '{print $1, $3, $7, $8, $10}'
    fi


        
}

view "$1"

